// Generated by https://quicktype.io

export interface Attendes {
  id:               string;
  firstName:        string;
  lastName:         string;
  eventId:          string;
  ticketIdentifier: string;
  checkedInAt:      Date | null;
}
